// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA84gi71qoSgdTt7eJE6Zc3Rv-2bnnhlTI',
    appId: '1:307106474993:web:4c172ec2b8964842ea7250',
    messagingSenderId: '307106474993',
    projectId: 'flutterfireuasira',
    authDomain: 'flutterfireuasira.firebaseapp.com',
    storageBucket: 'flutterfireuasira.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvPQJtbd6ZzU3isVd69xMr3M5ISUzbCQA',
    appId: '1:307106474993:android:ec595883e6ff6acbea7250',
    messagingSenderId: '307106474993',
    projectId: 'flutterfireuasira',
    storageBucket: 'flutterfireuasira.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcfh8aJMacSKc23fOt5MJGYOwisgkYpaA',
    appId: '1:307106474993:ios:406fdca62ac48946ea7250',
    messagingSenderId: '307106474993',
    projectId: 'flutterfireuasira',
    storageBucket: 'flutterfireuasira.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcfh8aJMacSKc23fOt5MJGYOwisgkYpaA',
    appId: '1:307106474993:ios:113545181d7f9250ea7250',
    messagingSenderId: '307106474993',
    projectId: 'flutterfireuasira',
    storageBucket: 'flutterfireuasira.appspot.com',
    iosBundleId: 'com.example.flutterlist.RunnerTests',
  );
}
